###
POST http://localhost:3000/api/neCoinTxn/sendNeCoins HTTP/1.1
content-type: application/json

{
  "address": "0x40e8fAf25Bac03674Cc3d5356c5A743B3213cCa5",
  "amount": "1.2333322"
}
###
POST http://localhost:3000/api/randomNumber/getRandom HTTP/1.1
content-type: application/json

{
  "clientSeed": "lUDWFcHXCg"
}
# result should be 33.04
###
POST http://localhost:3000/api/randomNumber/updateClientSeed HTTP/1.1
content-type: application/json

{
  "newClientSeed": "lUDWFcHXCgeud"
}